### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by adamevers** [ewiner/sonoslack#6]
Ran into this error:

`./index.iced
./index.iced: line 3: syntax error near unexpected token`('
./index.iced: line 3: `sonos = require('sonos')'`

Then I did:

`./node_modules/.bin/iced index.iced`

Which spit out this: 

```
SyntaxError: /Users/sprinklr/Desktop/sonoslack-master/config.json: Unexpected token /
  at Object.parse (native)
  at Object.Module._extensions..json (module.js:424:27)
  at Module.load (/Users/sprinklr/Desktop/sonoslack-master/node_modules/iced-coffee-script/lib/coffee-script/register.js:47:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/Users/sprinklr/Desktop/sonoslack-master/index.iced:16:10)
  at Object.<anonymous> (/Users/sprinklr/Desktop/sonoslack-master/index.iced:3:1)
  at Module._compile (module.js:409:26)
  at Object.exports.run (/Users/sprinklr/Desktop/sonoslack-master/node_modules/iced-coffee-script/lib/coffee-script/coffee-script.js:124:23)
  at compileScript (/Users/sprinklr/Desktop/sonoslack-master/node_modules/iced-coffee-script/lib/coffee-script/command.js:211:29)
  at compilePath (/Users/sprinklr/Desktop/sonoslack-master/node_modules/iced-coffee-script/lib/coffee-script/command.js:164:14)
  at Object.exports.run (/Users/sprinklr/Desktop/sonoslack-master/node_modules/iced-coffee-script/lib/coffee-script/command.js:99:21)
  at Object.<anonymous> (/Users/sprinklr/Desktop/sonoslack-master/node_modules/iced-coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:139:18)
  at node.js:968:3
```

Dug through the code but couldn't find anything to fix.

**Comment by ewiner** [comment]
In your `config.json`, can you try taking out the comments (the parts beginning with `//`)?

**Comment by dancarew** [comment]
I'm getting the same issue.  Took out comments; no luck.

**Comment by adamevers** [comment]
@ewiner - thanks for the quick response. Same error :(

**Comment by cyrilnigg** [comment]
I'm getting the same error as @adamevers
